### ISSUE TITLE
installation manager

### ISSUE THREAD

**Issue by Chal10** [platformio/platformio-core-installer#1750] opened 2021-10-15 09:33 UTC
I couldn't download the platformio-ide in Atom
Error: ENOENT: no such file or directory, mkdir 'C:\Users\User.platformio.cache' at fs.mkdirSync (fs.js:872:3) at Object.fs.mkdirSync (ELECTRON_ASAR.js:727:16) at v (C:\Users\User.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:7087) at Object.e.getTmpDir (C:\Users\User.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:5281) at f (C:\Users\User.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:888874) at e.callInstallerScript (C:\Users\User.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:33627) at t.value (C:\Users\User.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:27974) at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by ivankravets** [comment] 2021-11-05 11:15
Duplicate of https://github.com/platformio/platformio-core-installer/issues/1214

**Closed by ivankravets** 2021-11-05 11:15 UTC
