### ISSUE TITLE
Reporting as insntructed

### ISSUE THREAD

**Issue by Dan-Essin** [platformio/platformio-core-installer#2866] opened 2023-04-19 00:48 UTC
D:\Downloads>python get-platformio.py
Installer version: 1.1.2
Platform: Windows-10
Python version: 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
Python path: C:\Python\Python311\python.exe
Creating a virtual environment at C:\Users\Administrator\.platformio\penv
C:\Python\Python311\python.exe
Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues

**Comment by ivankravets** [comment] 2023-05-31 12:28
Duplicate of https://github.com/platformio/platformio-core-installer/issues/2955

**Closed by ivankravets** 2023-05-31 12:28 UTC
