### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Lucas-idp** [platformio/platformio-core-installer#155] opened 2020-09-27 22:15 UTC
# Description of problem Leave a comment... BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN - https://github.com/platformio/platformio-vscode-ide/issues?q=is:issue  # Configuration VSCode: 1.49.2 PIO IDE: v2.1.0 System: Windows_NT, 10.0.18362, x64 # Exception ``` Error:   WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001A6E6CF63C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/platformio/ WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001A6E6CF60C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/platformio/ WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001A6E6CF1848>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/platformio/ WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001A6E6CF18C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/platformio/ WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001A6E6CF1F88>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/platformio/ ERROR: Could not find a version that satisfies the requirement platformio (from versions: none) ERROR: No matching distribution found for platformio Error: Could not install PlatformIO Core: If you have antivirus/firewall/defender software in a system, try to disable it for a while. Command '['C:\\Users\\Lucas\\.platformio\\penv\\Scripts\\python.exe', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1. -> Installer version: 0.3.5 Platform: Windows-10 Python version: 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)] Python path: C:\Users\Lucas\.platformio\python3\python.exe Creating a virtual environment at C:\Users\Lucas\.platformio\penv Updating Python package manager (PIP) in a virtual environment Virtual environment has been successfully created! Installing PlatformIO Core Collecting platformio at c:\Users\Lucas\.vscode\extensions\platformio.platformio-ide-2.1.0\node_modules\platformio-node-helpers\dist\index.js:1:4911 at ChildProcess.s (c:\Users\Lucas\.vscode\extensions\platformio.platformio-ide-2.1.0\node_modules\platformio-node-helpers\dist\index.js:1:4807) at ChildProcess.emit (events.js:223:5) at ChildProcess.cp.emit (c:\Users\Lucas\.vscode\extensions\platformio.platformio-ide-2.1.0\node_modules\cross-spawn\lib\enoent.js:34:29) at maybeClose (internal/child_process.js:1021:16) at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) ```

**Comment by ivankravets** [comment] 2020-10-16 10:43
Duplicate of https://github.com/platformio/platformio-core-installer/issues/152

**Closed by ivankravets** 2020-10-16 10:43 UTC
