### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by jerrold00j** [platformio/platformio-core-installer#210] opened 2020-10-13 16:23 UTC
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.50.0
  PIO IDE: v2.1.0
  System: Windows_NT, 10.0.19041, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "C:\Users\jerrold gideon\.platformio\.cache\tmp\get-platformio-0.3.5.py", line 69, in <module>
    main()
  File "C:\Users\jerrold gideon\.platformio\.cache\tmp\get-platformio-0.3.5.py", line 61, in main
    bootstrap()
  File "C:\Users\jerrold gideon\.platformio\.cache\tmp\get-platformio-0.3.5.py", line 47, in bootstrap
    pioinstaller.__main__.main()
  File "C:\Users\jerrold gideon\.platformio\.cache\tmp\.piocore-installer-m520pf08\tmp9e99md23\pioinstaller.zip\pioinstaller\__main__.py", line 122, in main
  File "C:\Users\jerrold gideon\.platformio\.cache\tmp\.piocore-installer-m520pf08\tmp9e99md23\pioinstaller.zip\click\core.py", line 829, in __call__
  File "C:\Users\jerrold gideon\.platformio\.cache\tmp\.piocore-installer-m520pf08\tmp9e99md23\pioinstaller.zip\click\core.py", line 782, in main
  File "C:\Users\jerrold gideon\.platformio\.cache\tmp\.piocore-installer-m520pf08\tmp9e99md23\pioinstaller.zip\click\core.py", line 1236, in invoke
  File "C:\Users\jerrold gideon\.platformio\.cache\tmp\.piocore-installer-m520pf08\tmp9e99md23\pioinstaller.zip\click\core.py", line 1066, in invoke
  File "C:\Users\jerrold gideon\.platformio\.cache\tmp\.piocore-installer-m520pf08\tmp9e99md23\pioinstaller.zip\click\core.py", line 610, in invoke
  File "C:\Users\jerrold gideon\.platformio\.cache\tmp\.piocore-installer-m520pf08\tmp9e99md23\pioinstaller.zip\click\decorators.py", line 21, in new_func
  File "C:\Users\jerrold gideon\.platformio\.cache\tmp\.piocore-installer-m520pf08\tmp9e99md23\pioinstaller.zip\pioinstaller\__main__.py", line 52, in cli
  File "C:\Users\jerrold gideon\.platformio\.cache\tmp\.piocore-installer-m520pf08\tmp9e99md23\pioinstaller.zip\pioinstaller\core.py", line 72, in install_platformio_core
  File "C:\Users\jerrold gideon\.platformio\.cache\tmp\.piocore-installer-m520pf08\tmp9e99md23\pioinstaller.zip\pioinstaller\penv.py", line 75, in create_core_penv
  File "C:\Users\jerrold gideon\.platformio\.cache\tmp\.piocore-installer-m520pf08\tmp9e99md23\pioinstaller.zip\pioinstaller\penv.py", line 144, in add_state_info
  File "C:\Users\jerrold gideon\.platformio\python3\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Users\jerrold gideon\.platformio\python3\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Users\\jerrold gideon\\.platformio\\penv\\Scripts\\python.exe', '-c', "import sys

**Comment by ivankravets** [comment] 2020-10-16 10:53
Duplicate of https://github.com/platformio/platformio-core-installer/issues/221

**Closed by ivankravets** 2020-10-16 10:53 UTC
