### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by qiw377** [platformio/platformio-core-installer#3121] opened 2023-12-08 11:30 UTC
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.84.2
  PIO IDE: v3.3.1
  System: Windows_NT, 10.0.19045, x64

  %23 Exception
  ```
  Error:   ERROR: HTTP error 403 while getting https://pypi.tuna.tsinghua.edu.cn/packages/0b/d3/d379bfc94637caaf9bc42d6ed90b49af2a7d5aeab78806489307d186e601/platformio-6.1.11-py3-none-any.whl%23sha256=2bd7feb936f1b07b34f0556a47ab68a4f8764de39be30c636f216006f2e911ca (from https://pypi.tuna.tsinghua.edu.cn/simple/platformio/) (requires-python:>=3.6)
ERROR: Could not install requirement platformio from https://pypi.tuna.tsinghua.edu.cn/packages/0b/d3/d379bfc94637caaf9bc42d6ed90b49af2a7d5aeab78806489307d186e601/platformio-6.1.11-py3-none-any.whl%23sha256=2bd7feb936f1b07b34f0556a47ab68a4f8764de39be30c636f216006f2e911ca because of HTTP error 403 Client Error: Forbidden for url: https://pypi.tuna.tsinghua.edu.cn/packages/0b/d3/d379bfc94637caaf9bc42d6ed90b49af2a7d5aeab78806489307d186e601/platformio-6.1.11-py3-none-any.whl for URL https://pypi.tuna.tsinghua.edu.cn/packages/0b/d3/d379bfc94637caaf9bc42d6ed90b49af2a7d5aeab78806489307d186e601/platformio-6.1.11-py3-none-any.whl%23sha256=2bd7feb936f1b07b34f0556a47ab68a4f8764de39be30c636f216006f2e911ca (from https://pypi.tuna.tsinghua.edu.cn/simple/platformio/) (requires-python:>=3.6)
WARNING: There was an error checking the latest version of pip.
Error: Could not install PlatformIO Core: If you have antivirus/firewall/defender software in a system, try to disable it for a while.
 Command '['C:\\Users\\look\\.platformio\\penv\\Scripts\\python.exe', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.2.1
Platform: Windows-10
Python version: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
Python path: C:\Users\look\.platformio\python3\python.exe
Creating a virtual environment at C:\Users\look\.platformio\penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/
Collecting platformio

	at c:\Users\look\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5300
	at ChildProcess.c (c:\Users\look\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4598)
	at ChildProcess.emit (node:events:513:28)
	at ChildProcess.emit (node:domain:489:12)
	at maybeClose (node:internal/child_process:1091:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)
  ```

**Comment by ivankravets** [comment] 2024-01-06 12:06
Duplicate of https://github.com/platformio/platformio-core-installer/issues/3129

**Closed by ivankravets** 2024-01-06 12:06 UTC
