### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by idqaq** [platformio/platformio-core-installer#2333] opened 2022-08-04 07:34 UTC
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.68.1
  PIO IDE: v2.5.1
  System: Windows_NT, 10.0.19043, x64

  %23 Exception
  ```
  Error: Could not find compatible PlatformIO Core. Please enable `platformio-ide.useBuiltinPIOCore` setting and restart IDE.
	at f.value (c:\Users\Administrator\.vscode-oss\extensions\platformio.platformio-ide-2.5.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:801940)
	at E.install (c:\Users\Administrator\.vscode-oss\extensions\platformio.platformio-ide-2.5.1-win32-x64\dist\extension.js:1:4493)
	at c:\Users\Administrator\.vscode-oss\extensions\platformio.platformio-ide-2.5.1-win32-x64\dist\extension.js:1:27975
	at E._withProgress (d:\_APP\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:81:44253)
	at E.withProgress (d:\_APP\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:81:44007)
	at Object.withProgress (d:\_APP\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:42210)
	at Object.startInstaller (c:\Users\Administrator\.vscode-oss\extensions\platformio.platformio-ide-2.5.1-win32-x64\dist\extension.js:1:27390)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Object.activate (c:\Users\Administrator\.vscode-oss\extensions\platformio.platformio-ide-2.5.1-win32-x64\dist\extension.js:1:22838)
  ```

**Comment by ivankravets** [comment] 2022-08-12 11:14
Duplicate of https://github.com/platformio/platformio-core-installer/issues/2284

**Closed by ivankravets** 2022-08-12 11:14 UTC
