### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by firminoweb** [platformio/platformio-core-installer#3073] opened 2023-09-20 11:21 UTC
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.82.2
  PIO IDE: v3.3.1
  System: Linux, 6.2.0-32-generic, x64

  %23 Exception
  ```
  Error: WARNING: The index url "/usr/bin/python3" seems invalid, please provide a scheme.
WARNING: Location '/usr/bin/python3/platformio/' is ignored: it is either a non-existing path or lacks a specific scheme.
ERROR: Could not find a version that satisfies the requirement platformio (from versions: none)
ERROR: No matching distribution found for platformio
Error: Could not install PlatformIO Core: Command '['/home/firmino/.platformio/penv/bin/python', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.2.1
Platform: Linux-6.2.0-32-generic-x86_64-with-glibc2.35
Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Python path: /usr/bin/python3
Creating a virtual environment at /home/firmino/.platformio/penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core
Looking in indexes: /usr/bin/python3

    at /home/firmino/.vscode/extensions/platformio.platformio-ide-3.3.1-linux-x64/node_modules/platformio-node-helpers/dist/index.js:1:5300
    at ChildProcess.c (/home/firmino/.vscode/extensions/platformio.platformio-ide-3.3.1-linux-x64/node_modules/platformio-node-helpers/dist/index.js:1:4598)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:322:12)
  ```

**Comment by ivankravets** [comment] 2024-01-06 11:31
Duplicate of https://github.com/platformio/platformio-core-installer/issues/3129

**Closed by ivankravets** 2024-01-06 11:31 UTC
