### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Gustavo-24** [platformio/platformio-core-installer#161] opened 2020-09-29 00:56 UTC
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.49.2
  PIO IDE: v2.1.0
  System: Linux, 4.19.0-11-amd64, x64

  %23 Exception
  ```
  Error: Error: Can not install PlatformIO Core due to a missed `distutils` package in your Python installation.
Please install this package manually using the OS package manager. For example:

$ apt-get install python3-distutils

(MAY require administrator access `sudo`)
 -> Installer version: 0.3.5
Platform: Linux-4.19.0-11-amd64-x86_64-with-glibc2.28
Python version: 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0]
Python path: /usr/bin/python3
Creating a virtual environment at /home/gustavo/.platformio/penv

	at /home/gustavo/.vscode/extensions/platformio.platformio-ide-2.1.0/node_modules/platformio-node-helpers/dist/index.js:1:4911
	at ChildProcess.s (/home/gustavo/.vscode/extensions/platformio.platformio-ide-2.1.0/node_modules/platformio-node-helpers/dist/index.js:1:4807)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:223:5)
	at Pipe.<anonymous> (net.js:664:12)
  ```

**Comment by ivankravets** [comment] 2020-10-16 10:45
Duplicate of https://github.com/platformio/platformio-core-installer/issues/85

**Closed by ivankravets** 2020-10-16 10:45 UTC
