### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by 521168queen** [platformio/platformio-core-installer#568] opened 2021-03-07 10:31 UTC
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.54.1
  PIO IDE: v2.3.0
  System: Linux, 5.8.0-44-generic, x64

  %23 Exception
  ```
  Error: Error: Can not install PlatformIO Core due to a missed `distutils` package in your Python installation.
Please install this package manually using the OS package manager. For example:

$ apt-get install python3-venv

(MAY require administrator access `sudo`)
 -> Installer version: 1.0.0
Platform: Linux-5.8.0-44-generic-x86_64-with-glibc2.29
Python version: 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0]
Python path: /usr/bin/python3
Creating a virtual environment at /home/wjq/.platformio/penv

	at /home/wjq/.vscode/extensions/platformio.platformio-ide-2.3.0/node_modules/platformio-node-helpers/dist/index.js:1:930873
	at ChildProcess.c (/home/wjq/.vscode/extensions/platformio.platformio-ide-2.3.0/node_modules/platformio-node-helpers/dist/index.js:1:930767)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.EventEmitter.emit (domain.js:483:12)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
  ```

**Comment by ivankravets** [comment] 2021-03-07 11:51
Duplicate of https://github.com/platformio/platformio-core-installer/issues/568

**Closed by ivankravets** 2021-03-07 11:51 UTC
