### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Resurrection2981** [platformio/platformio-core-installer#3094] opened 2023-10-28 02:09 UTC
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.83.1
  PIO IDE: v3.3.1
  System: Windows_NT, 10.0.22621, x64

  %23 Exception
  ```
  Error:   error: subprocess-exited-with-error
  
  pip subprocess to install build dependencies did not run successfully.
  exit code: 1
  
  [5 lines of output]
  ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
  ERROR: No matching distribution found for setuptools>=40.8.0
  
  [notice] A new release of pip is available: 23.1.2 -> 23.3.1
  [notice] To update, run: C:\Users\Resurrection\.platformio\penv\Scripts\python.exe -m pip install --upgrade pip
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

pip subprocess to install build dependencies did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 23.1.2 -> 23.3.1
[notice] To update, run: C:\Users\Resurrection\.platformio\penv\Scripts\python.exe -m pip install --upgrade pip
Error: Could not install PlatformIO Core: If you have antivirus/firewall/defender software in a system, try to disable it for a while.
 Command '['C:\\Users\\Resurrection\\.platformio\\penv\\Scripts\\python.exe', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.2.1
Platform: Windows-10
Python version: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
Python path: C:\Users\Resurrection\.platformio\python3\python.exe
Creating a virtual environment at C:\Users\Resurrection\.platformio\penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core
Collecting platformio
  Downloading platformio-6.1.11-py3-none-any.whl (416 kB)
     -------------------------------------- 416.9/416.9 kB 6.4 kB/s eta 0:00:00
Collecting bottle==0.12.* (from platformio)
  Downloading bottle-0.12.25-py3-none-any.whl (90 kB)
     --------------------------------------- 90.2/90.2 kB 25.7 kB/s eta 0:00:00
Collecting click<=8.2,>=8.0.4 (from platformio)
  Downloading click-8.1.7-py3-none-any.whl (97 kB)
     --------------------------------------- 97.9/97.9 kB 15.0 kB/s eta 0:00:00
Collecting colorama (from platformio)
  Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
INFO: pip is looking at multiple versions of platformio to determine which version is compatible with other requirements. This could take a while.
Collecting platformio
  Downloading platformio-6.1.10-py3-none-any.whl (416 kB)
     ------------------------------------- 416.9/416.9 kB 25.2 kB/s eta 0:00:00
  Downloading platformio-6.1.9-py3-none-any.whl (418 kB)
     ------------------------------------- 418.9/418.9 kB 29.5 kB/s eta 0:00:00
Collecting pyelftools==0.29 (from platformio)
  Using cached pyelftools-0.29-py2.py3-none-any.whl (174 kB)
Collecting pyserial==3.5.* (from platformio)
  Downloading pyserial-3.5-py2.py3-none-any.whl (90 kB)
     --------------------------------------- 90.6/90.6 kB 45.1 kB/s eta 0:00:00
Collecting requests==2.* (from platformio)
  Downloading requests-2.31.0-py3-none-any.whl (62 kB)
     --------------------------------------- 62.6/62.6 kB 28.4 kB/s eta 0:00:00
Collecting semantic-version==2.10.* (from platformio)
  Using cached semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
Collecting tabulate==0.* (from platformio)
  Using cached tabulate-0.9.0-py3-none-any.whl (35 kB)
Collecting aiofiles>=0.8.0 (from platformio)
  Downloading aiofiles-23.2.1-py3-none-any.whl (15 kB)
Collecting ajsonrpc==1.2.* (from platformio)
  Using cached ajsonrpc-1.2.0-py3-none-any.whl (22 kB)
Collecting platformio
  Downloading platformio-6.1.8-py3-none-any.whl (418 kB)
     ------------------------------------- 418.9/418.9 kB 20.6 kB/s eta 0:00:00
  Downloading platformio-6.1.7-py3-none-any.whl (418 kB)
     ------------------------------------- 419.0/419.0 kB 17.9 kB/s eta 0:00:00
  Downloading platformio-6.1.6.tar.gz (236 kB)
     ------------------------------------- 236.4/236.4 kB 38.1 kB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'

	at c:\Users\Resurrection\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5300
	at ChildProcess.c (c:\Users\Resurrection\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4598)
	at ChildProcess.emit (node:events:513:28)
	at ChildProcess.emit (node:domain:489:12)
	at maybeClose (node:internal/child_process:1091:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)
  ```

**Comment by ivankravets** [comment] 2024-01-06 11:30
Duplicate of https://github.com/platformio/platformio-core-installer/issues/3129

**Closed by ivankravets** 2024-01-06 11:30 UTC
