### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by antiguaMob** [platformio/platformio-core-installer#53] opened 2020-07-28 21:56 UTC
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.47.3
  PIO IDE: v2.0.0-beta.5
  System: Windows_NT, 10.0.18363, x64

  %23 Exception
  ```
  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
	at validateString (internal/validators.js:112:11)
	at Object.dirname (path.js:583:5)
	at t.value (c:\Users\antigua\.vscode\extensions\platformio.platformio-ide-2.0.0-beta.5\node_modules\platformio-node-helpers\dist\index.js:1:28362)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async t.value (c:\Users\antigua\.vscode\extensions\platformio.platformio-ide-2.0.0-beta.5\node_modules\platformio-node-helpers\dist\index.js:1:27140)
	at async Promise.all (index 0)
	at async c:\Users\antigua\.vscode\extensions\platformio.platformio-ide-2.0.0-beta.5\dist\extension.js:1:5946
  ```

**Comment by ivankravets** [comment] 2020-09-11 12:46
Duplicate of https://github.com/platformio/platformio-core-installer/issues/54

**Closed by ivankravets** 2020-09-11 12:46 UTC
