### ISSUE TITLE
Compatible PlatformIO Core not found

### ISSUE THREAD

**Issue by Tom-Yucw** [platformio/platformio-core-installer#1996] opened 2022-03-01 12:55 UTC
I installed PlatformIO in Ubuntu 18.0.4 in VirtualBox. Then I can open home correctly.

But when I restart my ubuntu system in VirtualBox, something is upgraded automatically.

Then open VSCode, open Home, but home page cannot be opened.

From console log, I found the following message:
Error: Error: Compatible PlatformIO Core not found.Reason: PlatformIO Core was installed using another platform **Linux-5.4.0-84-generic-x86_64-with-glibc2.25**. Your current platform: **Linux-5.4.0-100-generic-x86_64-with-glibc2.25**	at /home/xxx/.vscode/extensions/platformio.platformio-ide-5.2.0/dist/extension.js:1:2634	at ChildProcess.c (/home/xxx/.vscode/extensions/platformio.platformio-ide-5.2.0/dist/extension.js:1:2528)	at ChildProcess.emit (events.js:315:20)	at ChildProcess.EventEmitter.emit (domain.js:467:12)	at maybeClose (internal/child_process.js:1048:16)	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)

That is to say, the platform upgraded from "**Linux-5.4.0-84**" to "**Linux-5.4.0-100**", which made the failure of opening home page.

It is funny that I can run/debug my code correctly. Only home cannot be opened.

Is there some ways to make it compatible to this upgrade?

**Comment by ivankravets** [comment] 2022-03-05 14:58
Do you use the latest versions of VSCode and PlatformIO IDE for VSCode?

**Comment by Tom-Yucw** [comment] 2022-03-14 02:23
Sorry for this answer comes so late.
I have found the reason.

In the plugin code of `await this.startInstaller(!hasPIOProject);`, main flow is described bellow:
`<- await this.startInstaller(!hasPIOProject);
<- const im = new InstallationManager(this.context.globalState, disableAutoUpdates);
<- new pioNodeHelpers.installer.PlatformIOCoreStage(......)
<- im.check()
<- await this.loadCoreState();
<- console.info(await callInstallerScript(await this.whereIsPython(), scriptArgs));   --here call get-platfrom.py
    // Load PIO Core state
    const coreState = await misc.loadJSON(stateJSONPath);
    console.info('PIO Core State', coreState);
    **core.setCoreState(coreState);  --here marked as pos1**

<- get-platfrom.py: pioinstaller.zip: core.py: _check_platform_version:
    state = penv.load_state()
    if state.get("platform") != platform.platform(terse=True):   --here, after some upgrade of ubuntu, platform.platform(terse=True) changes, which makes it not equal to the string stored in penv\state.json
        raise exception.InvalidPlatformIOCore(
            "PlatformIO Core was installed using another platform `%s`. "
            "Your current platform: %s"
            % (state.get("platform"), platform.platform(terse=True))
        )

---so, except is raised when calling get-platfrom.py, which cause **core.setCoreState(coreState);** in **pos1** is not executed, _CORE_STATE is not set`

When I toggled home page, 
` vscode.commands.registerCommand('platformio-ide.showHome', (startUrl) =>this.pioHome.toggle(startUrl))
 <- async toggle(startUrl = PIOHome.defaultStartUrl){
    this._currentPanel.webview.html = await this.getWebviewContent(startUrl);
  }
 <-  async getWebviewContent(startUrl){
    await pioNodeHelpers.home.ensureServerStarted
  }
 <- ensureServerStarted -> _ensureServerStarted -> runPIOCommand
 <- runPIOCommand{ await getCorePythonExe() }
 <- export async function getCorePythonExe() {
    const result = getCoreState().python_exe;   ---here, getCoreState will get **undefined|{}**, so no python_exe will be assigned
  }
 <-export async function getCorePythonExe() {
  const result = getCoreState().python_exe;
  if (!result) {
    throw new Error('Rivai Core is not installed');  --here raised the error for no python, but actually I had one
  }
  return result;
}`

**Comment by ivankravets** [comment] 2022-06-22 15:09
Duplicate of https://github.com/platformio/platformio-core-installer/issues/644

**Closed by ivankravets** 2022-06-22 15:09 UTC
Labels: enhancement
