### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by fangyygw** [platformio/platformio-core-installer#3083] opened 2023-10-10 08:46 UTC
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.83.0
  PIO IDE: v3.3.1
  System: Darwin, 23.0.0, x64

  %23 Exception
  ```
  Error: ERROR: Could not find a version that satisfies the requirement platformio (from versions: none)
ERROR: No matching distribution found for platformio
Error: Could not install PlatformIO Core: Command '['/Users/fangzhen/.platformio/penv/bin/python', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.2.1
Platform: macOS-10.16
Python version: 3.9.9 (main, Nov 29 2021, 12:55:48) 
[Clang 10.0.0 (clang-1000.10.44.4)]
Python path: /Users/fangzhen/.platformio/python3/bin/python3
Creating a virtual environment at /Users/fangzhen/.platformio/penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core

    at /Users/fangzhen/.vscode/extensions/platformio.platformio-ide-3.3.1-darwin-x64/node_modules/platformio-node-helpers/dist/index.js:1:5300
    at ChildProcess.c (/Users/fangzhen/.vscode/extensions/platformio.platformio-ide-3.3.1-darwin-x64/node_modules/platformio-node-helpers/dist/index.js:1:4598)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:322:12)
  ```

**Comment by ivankravets** [comment] 2024-01-06 11:30
Duplicate of https://github.com/platformio/platformio-core-installer/issues/3129

**Closed by ivankravets** 2024-01-06 11:30 UTC
