### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Slavka1967** [platformio/platformio-core-installer#2932] opened 2023-05-14 10:37 UTC
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.78.2
  PIO IDE: v3.1.1
  System: Windows_NT, 10.0.19045, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Admin\.platformio\python3\lib\multiprocessing\spawn.py", line 107, in spawn_main
    new_handle = reduction.duplicate(pipe_handle,
  File "C:\Users\Admin\.platformio\python3\lib\multiprocessing\reduction.py", line 79, in duplicate
    return _winapi.DuplicateHandle(
PermissionError: [WinError 5] \u041e\u0442\u043a\u0430\u0437\u0430\u043d\u043e \u0432 \u0434\u043e\u0441\u0442\u0443\u043f\u0435
Traceback (most recent call last):
  File "C:\Users\Admin\.platformio\.cache\tmp\get-platformio-1.1.2.py", line 69, in <module>
    main()
  File "C:\Users\Admin\.platformio\.cache\tmp\get-platformio-1.1.2.py", line 61, in main
    bootstrap()
  File "C:\Users\Admin\.platformio\.cache\tmp\get-platformio-1.1.2.py", line 47, in bootstrap
    pioinstaller.__main__.main()
  File "C:\Users\Admin\.platformio\.cache\tmp\.piocore-installer-11eujx3k\tmp9ejj8p1n\pioinstaller.zip\pioinstaller\__main__.py", line 133, in main
  File "C:\Users\Admin\.platformio\.cache\tmp\.piocore-installer-11eujx3k\tmp9ejj8p1n\pioinstaller.zip\click\core.py", line 1128, in __call__
  File "C:\Users\Admin\.platformio\.cache\tmp\.piocore-installer-11eujx3k\tmp9ejj8p1n\pioinstaller.zip\click\core.py", line 1053, in main
  File "C:\Users\Admin\.platformio\.cache\tmp\.piocore-installer-11eujx3k\tmp9ejj8p1n\pioinstaller.zip\click\core.py", line 1637, in invoke
  File "C:\Users\Admin\.platformio\.cache\tmp\.piocore-installer-11eujx3k\tmp9ejj8p1n\pioinstaller.zip\click\core.py", line 1395, in invoke
  File "C:\Users\Admin\.platformio\.cache\tmp\.piocore-installer-11eujx3k\tmp9ejj8p1n\pioinstaller.zip\click\core.py", line 754, in invoke
  File "C:\Users\Admin\.platformio\.cache\tmp\.piocore-installer-11eujx3k\tmp9ejj8p1n\pioinstaller.zip\click\decorators.py", line 26, in new_func
  File "C:\Users\Admin\.platformio\.cache\tmp\.piocore-installer-11eujx3k\tmp9ejj8p1n\pioinstaller.zip\pioinstaller\__main__.py", line 61, in cli
  File "C:\Users\Admin\.platformio\.cache\tmp\.piocore-installer-11eujx3k\tmp9ejj8p1n\pioinstaller.zip\pioinstaller\core.py", line 70, in install_platformio_core
  File "C:\Users\Admin\.platformio\.cache\tmp\.piocore-installer-11eujx3k\tmp9ejj8p1n\pioinstaller.zip\pioinstaller\core.py", line 98, in _install_platformio_core
  File "C:\Users\Admin\.platformio\.cache\tmp\.piocore-installer-11eujx3k\tmp9ejj8p1n\pioinstaller.zip\pioinstaller\penv.py", line 71, in create_core_penv
  File "C:\Users\Admin\.platformio\.cache\tmp\.piocore-installer-11eujx3k\tmp9ejj8p1n\pioinstaller.zip\pioinstaller\penv.py", line 141, in init_state
  File "C:\Users\Admin\.platformio\python3\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\Admin\.platformio\python3\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Admin\.platformio\python3\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Admin\.platformio\python3\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 87] \u041f\u0430\u0440\u0430\u043c\u0435\u0442\u0440 \u0437\u0430\u0434\u0430\u043d \u043d\u0435\u0432\u0435\u0440\u043d\u043e
 -> Installer version: 1.1.2
Platform: Windows-10
Python version: 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)]
Python path: C:\Users\Admin\.platformio\python3\python.exe
Creating a virtual environment at C:\Users\Admin\.platformio\penv

	at c:\Users\Admin\.vscode\extensions\platformio.platformio-ide-3.1.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5303
	at ChildProcess.o (c:\Users\Admin\.vscode\extensions\platformio.platformio-ide-3.1.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4601)
	at ChildProcess.emit (node:events:513:28)
	at ChildProcess.emit (node:domain:489:12)
	at maybeClose (node:internal/child_process:1112:16)
	at ChildProcess._handle.onexit (node:internal/child_process:304:5)
  ```

**Comment by ivankravets** [comment] 2023-05-31 12:17
Duplicate of https://github.com/platformio/platformio-vscode-ide/issues/884

**Closed by ivankravets** 2023-05-31 12:17 UTC
