### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by SyncRone157** [platformio/platformio-core-installer#2586] opened 2022-11-20 12:28 UTC
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.73.1
  PIO IDE: v2.5.5
  System: Linux, 5.15.0-53-generic, x64

  %23 Exception
  ```
  Error: Error: Compatible PlatformIO Core not found.
Reason: Could not run `/home/stanislav/.platformio/penv/bin/platformio --help`.
Error: Error: Traceback (most recent call last):
  File "/home/stanislav/.platformio/penv/lib/python3.10/site-packages/platformio/__main__.py", line 102, in main
    cli()  %23 pylint: disable=no-value-for-parameter
  File "/home/stanislav/.platformio/penv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/stanislav/.platformio/penv/lib/python3.10/site-packages/click/core.py", line 1054, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/home/stanislav/.platformio/penv/lib/python3.10/site-packages/click/core.py", line 920, in make_context
    self.parse_args(ctx, args)
  File "/home/stanislav/.platformio/penv/lib/python3.10/site-packages/click/core.py", line 1613, in parse_args
    rest = super().parse_args(ctx, args)
  File "/home/stanislav/.platformio/penv/lib/python3.10/site-packages/click/core.py", line 1378, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/stanislav/.platformio/penv/lib/python3.10/site-packages/click/core.py", line 2360, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/home/stanislav/.platformio/penv/lib/python3.10/site-packages/click/core.py", line 2322, in process_value
    value = self.callback(ctx, self, value)
  File "/home/stanislav/.platformio/penv/lib/python3.10/site-packages/click/core.py", line 1273, in show_help
    echo(ctx.get_help(), color=ctx.color)
  File "/home/stanislav/.platformio/penv/lib/python3.10/site-packages/click/core.py", line 699, in get_help
    return self.command.get_help(self)
  File "/home/stanislav/.platformio/penv/lib/python3.10/site-packages/click/core.py", line 1298, in get_help
    self.format_help(ctx, formatter)
  File "/home/stanislav/.platformio/penv/lib/python3.10/site-packages/click/core.py", line 1331, in format_help
    self.format_options(ctx, formatter)
  File "/home/stanislav/.platformio/penv/lib/python3.10/site-packages/click/core.py", line 1533, in format_options
    self.format_commands(ctx, formatter)
  File "/home/stanislav/.platformio/penv/lib/python3.10/site-packages/click/core.py", line 1586, in format_commands
    cmd = self.get_command(ctx, subcommand)
  File "/home/stanislav/.platformio/penv/lib/python3.10/site-packages/platformio/cli.py", line 80, in get_command
    module = importlib.import_module(commands[cmd_name])
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/stanislav/.platformio/penv/lib/python3.10/site-packages/platformio/commands/ci.py", line 24, in <module>
    from platformio.project.commands.init import project_init_cmd, validate_boards
  File "/home/stanislav/.platformio/penv/lib/python3.10/site-packages/platformio/project/commands/init.py", line 55, in <module>
    @click.option("--ide", type=click.Choice(ProjectGenerator.get_supported_ides()))
  File "/home/stanislav/.platformio/penv/lib/python3.10/site-packages/platformio/project/integration/generator.py", line 62, in get_supported_ides
    for name in os.listdir(tpls_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/stanislav/.platformio/penv/lib/python3.10/site-packages/platformio/assets/templates/ide-projects'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq/index.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================



	at /home/stanislav/.vscode/extensions/platformio.platformio-ide-2.5.5-linux-x64/node_modules/platformio-node-helpers/dist/index.js:1:5311
	at ChildProcess.o (/home/stanislav/.vscode/extensions/platformio.platformio-ide-2.5.5-linux-x64/node_modules/platformio-node-helpers/dist/index.js:1:4691)
	at ChildProcess.emit (node:events:526:28)
	at ChildProcess.emit (node:domain:475:12)
	at maybeClose (node:internal/child_process:1092:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)
  ```

**Comment by ivankravets** [comment] 2022-11-25 00:28
Duplicate of https://github.com/platformio/platformio-core-installer/issues/2620

**Closed by ivankravets** 2022-11-25 00:28 UTC
