### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by AayushBoliya** [platformio/platformio-core-installer#407] opened 2020-12-27 19:49 UTC
%23 Configuration

  VSCode: 1.52.1
  PIO IDE: v2.2.1
  System: Windows_NT, 10.0.17763, x64

  %23 Exception
  ```
  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
	at validateString (internal/validators.js:112:11)
	at Object.dirname (path.js:583:5)
	at d.value (c:\Users\Aayush Boliya\.vscode\extensions\platformio.platformio-ide-2.2.1\node_modules\platformio-node-helpers\dist\index.js:1:872685)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async d.value (c:\Users\Aayush Boliya\.vscode\extensions\platformio.platformio-ide-2.2.1\node_modules\platformio-node-helpers\dist\index.js:1:870529)
	at async t.default.install (c:\Users\Aayush Boliya\.vscode\extensions\platformio.platformio-ide-2.2.1\dist\extension.js:1:6521)
	at async c:\Users\Aayush Boliya\.vscode\extensions\platformio.platformio-ide-2.2.1\dist\extension.js:1:12506
  ```

**Comment by ivankravets** [comment] 2021-01-21 18:14
Duplicate of https://github.com/platformio/platformio-core-installer/issues/90

**Closed by ivankravets** 2021-01-21 18:14 UTC
