### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by otm0937** [platformio/platformio-core-installer#431] opened 2021-01-09 06:36 UTC
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.52.1
  PIO IDE: v2.2.1
  System: Windows_NT, 10.0.19042, x64

  %23 Exception
  ```
  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.pythonPrompt [as dirname] (path.js:583:5)
    at d.value (c:\Users\otm09\.vscode\extensions\platformio.platformio-ide-2.2.1\node_modules\platformio-node-helpers\dist\webpack:\platformio-node-helpers\src\installer\stages\platformio-core.js:224:37)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at d.value (c:\Users\otm09\.vscode\extensions\platformio.platformio-ide-2.2.1\node_modules\platformio-node-helpers\dist\webpack:\platformio-node-helpers\src\installer\stages\platformio-core.js:107:20)
    at t.default.install (c:\Users\otm09\.vscode\extensions\platformio.platformio-ide-2.2.1\dist\webpack:\platformio-ide\src\installer\manager.js:86:57)
    at c:\Users\otm09\.vscode\extensions\platformio.platformio-ide-2.2.1\dist\webpack:\platformio-ide\src\main.js:209:36
  ```

**Comment by ivankravets** [comment] 2021-01-21 18:14
Duplicate of https://github.com/platformio/platformio-core-installer/issues/90

**Closed by ivankravets** 2021-01-21 18:14 UTC
