### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Drw-start** [platformio/platformio-core-installer#3109] opened 2023-11-13 01:28 UTC
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.84.2
  PIO IDE: v3.3.1
  System: Windows_NT, 10.0.22635, x64

  %23 Exception
  ```
  Error: Error: spawn C:\Users\Drw\.platformio\python3\python.exe ENOENT
	at c:\Users\Drw\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5300
	at c (c:\Users\Drw\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4598)
	at ChildProcess.<anonymous> (c:\Users\Drw\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5158)
	at ChildProcess.emit (node:events:513:28)
	at ChildProcess.emit (node:domain:489:12)
	at ChildProcess._handle.onexit (node:internal/child_process:289:12)
	at onErrorNT (node:internal/child_process:476:16)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
  ```

**Comment by ivankravets** [comment] 2024-01-06 12:13
Duplicate of https://github.com/platformio/platformio-core-installer/issues/3111

**Closed by ivankravets** 2024-01-06 12:13 UTC
