### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by AERCR3** [platformio/platformio-core-installer#3110] opened 2023-11-18 14:54 UTC
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.84.2
  PIO IDE: v3.3.1
  System: Windows_NT, 10.0.19045, x64

  %23 Exception
  ```
  Error:   error: subprocess-exited-with-error
  
  pip subprocess to install build dependencies did not run successfully.
  exit code: 1
  
  [5 lines of output]
  ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
  ERROR: No matching distribution found for setuptools>=40.8.0
  
  [notice] A new release of pip is available: 23.1.2 -> 23.3.1
  [notice] To update, run: C:\Users\cheng\.platformio\penv\Scripts\python.exe -m pip install --upgrade pip
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

pip subprocess to install build dependencies did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 23.1.2 -> 23.3.1
[notice] To update, run: C:\Users\cheng\.platformio\penv\Scripts\python.exe -m pip install --upgrade pip
Error: Could not install PlatformIO Core: If you have antivirus/firewall/defender software in a system, try to disable it for a while.
 Command '['C:\\Users\\cheng\\.platformio\\penv\\Scripts\\python.exe', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.2.1
Platform: Windows-10
Python version: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
Python path: C:\Users\cheng\.platformio\python3\python.exe
Creating a virtual environment at C:\Users\cheng\.platformio\penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core
Collecting platformio
  Downloading platformio-6.1.11-py3-none-any.whl (416 kB)
     -------------------------------------- 416.9/416.9 kB 9.2 kB/s eta 0:00:00
INFO: pip is looking at multiple versions of platformio to determine which version is compatible with other requirements. This could take a while.
  Downloading platformio-6.1.10-py3-none-any.whl (416 kB)
     -------------------------------------- 416.9/416.9 kB 7.9 kB/s eta 0:00:00
  Downloading platformio-6.1.9-py3-none-any.whl (418 kB)
     -------------------------------------- 418.9/418.9 kB 9.0 kB/s eta 0:00:00
  Downloading platformio-6.1.8-py3-none-any.whl (418 kB)
     -------------------------------------- 418.9/418.9 kB 8.9 kB/s eta 0:00:00
  Downloading platformio-6.1.7-py3-none-any.whl (418 kB)
     -------------------------------------- 419.0/419.0 kB 8.8 kB/s eta 0:00:00
  Downloading platformio-6.1.6.tar.gz (236 kB)
     ------------------------------------- 236.4/236.4 kB 10.5 kB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'

	at c:\Users\cheng\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5300
	at ChildProcess.c (c:\Users\cheng\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4598)
	at ChildProcess.emit (node:events:513:28)
	at ChildProcess.emit (node:domain:489:12)
	at maybeClose (node:internal/child_process:1091:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)
  ```

**Comment by ivankravets** [comment] 2024-01-06 11:28
Duplicate of https://github.com/platformio/platformio-core-installer/issues/3129

**Closed by ivankravets** 2024-01-06 11:28 UTC
