### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by putyavka** [platformio/platformio-core-installer#1804] opened 2021-11-04 11:54 UTC
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.61.2
  PIO IDE: v2.3.4
  System: Windows_NT, 10.0.19043, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "C:\Users\User\.platformio\.cache\tmp\get-platformio-1.0.3.py", line 69, in <module>
    main()
  File "C:\Users\User\.platformio\.cache\tmp\get-platformio-1.0.3.py", line 61, in main
    bootstrap()
  File "C:\Users\User\.platformio\.cache\tmp\get-platformio-1.0.3.py", line 47, in bootstrap
    pioinstaller.__main__.main()
  File "C:\Users\User\.platformio\.cache\tmp\.piocore-installer-1ycijuwx\tmprgr1t9h_\pioinstaller.zip\pioinstaller\__main__.py", line 131, in main
  File "C:\Users\User\.platformio\.cache\tmp\.piocore-installer-1ycijuwx\tmprgr1t9h_\pioinstaller.zip\click\core.py", line 1137, in __call__
  File "C:\Users\User\.platformio\.cache\tmp\.piocore-installer-1ycijuwx\tmprgr1t9h_\pioinstaller.zip\click\core.py", line 1062, in main
  File "C:\Users\User\.platformio\.cache\tmp\.piocore-installer-1ycijuwx\tmprgr1t9h_\pioinstaller.zip\click\core.py", line 1646, in invoke
  File "C:\Users\User\.platformio\.cache\tmp\.piocore-installer-1ycijuwx\tmprgr1t9h_\pioinstaller.zip\click\core.py", line 1404, in invoke
  File "C:\Users\User\.platformio\.cache\tmp\.piocore-installer-1ycijuwx\tmprgr1t9h_\pioinstaller.zip\click\core.py", line 763, in invoke
  File "C:\Users\User\.platformio\.cache\tmp\.piocore-installer-1ycijuwx\tmprgr1t9h_\pioinstaller.zip\click\decorators.py", line 26, in new_func
  File "C:\Users\User\.platformio\.cache\tmp\.piocore-installer-1ycijuwx\tmprgr1t9h_\pioinstaller.zip\pioinstaller\__main__.py", line 61, in cli
  File "C:\Users\User\.platformio\.cache\tmp\.piocore-installer-1ycijuwx\tmprgr1t9h_\pioinstaller.zip\pioinstaller\core.py", line 67, in install_platformio_core
  File "C:\Users\User\.platformio\.cache\tmp\.piocore-installer-1ycijuwx\tmprgr1t9h_\pioinstaller.zip\pioinstaller\core.py", line 95, in _install_platformio_core
  File "C:\Users\User\.platformio\.cache\tmp\.piocore-installer-1ycijuwx\tmprgr1t9h_\pioinstaller.zip\pioinstaller\penv.py", line 58, in create_core_penv
  File "C:\Users\User\.platformio\.cache\tmp\.piocore-installer-1ycijuwx\tmprgr1t9h_\pioinstaller.zip\pioinstaller\python.py", line 70, in fetch_portable_python
  File "C:\Users\User\.platformio\.cache\tmp\.piocore-installer-1ycijuwx\tmprgr1t9h_\pioinstaller.zip\pioinstaller\python.py", line 109, in get_portable_python_url
AttributeError: 'dict' object has no attribute 'name'
 -> Installer version: 1.0.3
Platform: Windows-10
Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
Python path: C:\Python39\python.exe
Creating a virtual environment at C:\Users\User\.platformio\penv
C:\Python39\python.exe

	at c:\Users\User\.vscode\extensions\platformio.platformio-ide-2.3.4\node_modules\platformio-node-helpers\dist\index.js:1:769806
	at ChildProcess.a (c:\Users\User\.vscode\extensions\platformio.platformio-ide-2.3.4\node_modules\platformio-node-helpers\dist\index.js:1:771396)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.EventEmitter.emit (domain.js:467:12)
	at ChildProcess.cp.emit (c:\Users\User\.vscode\extensions\platformio.platformio-ide-2.3.4\node_modules\cross-spawn\lib\enoent.js:34:29)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
  ```

**Comment by ivankravets** [comment] 2021-11-04 16:04
Duplicate of https://github.com/platformio/platformio-core-installer/issues/1778

**Closed by ivankravets** 2021-11-04 16:04 UTC
Labels: bug
