### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by singhkushwahmanvendra** [platformio/platformio-core-installer#551] opened 2021-03-05 07:02 UTC
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.53.2
  PIO IDE: v2.3.0
  System: Windows_NT, 10.0.19041, x64

  %23 Exception
  ```
  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
	at validateString (internal/validators.js:120:11)
	at Object.dirname (path.js:583:5)
	at E.value (c:\Users\MANVENDRA\.vscode\extensions\platformio.platformio-ide-2.3.0\node_modules\platformio-node-helpers\dist\index.js:1:924600)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async E.value (c:\Users\MANVENDRA\.vscode\extensions\platformio.platformio-ide-2.3.0\node_modules\platformio-node-helpers\dist\index.js:1:923268)
	at async t.default.install (c:\Users\MANVENDRA\.vscode\extensions\platformio.platformio-ide-2.3.0\dist\extension.js:1:6509)
	at async c:\Users\MANVENDRA\.vscode\extensions\platformio.platformio-ide-2.3.0\dist\extension.js:1:12420
  ```

**Comment by ivankravets** [comment] 2021-03-22 20:02
Have you resolved this issue?

**Comment by ivankravets** [comment] 2021-03-23 15:35
Duplicate of https://github.com/platformio/platformio-core-installer/issues/533

**Closed by ivankravets** 2021-03-23 15:35 UTC
Labels: help wanted
