### ISSUE TITLE
Thanks to all the platforms for allowing me, a fan like me, to learn relevant content and knowledge. This esp32 ardunio development platform platform io ran normally for the first two days, burned in the code and submitted the file system to build my own remote web page. However, in the past two days, this error has been reported and I don’t know how to solve it. Even the operating system has failed. I have changed it. Is this a problem with my computer or an error with the Paltform io official website?

### ISSUE THREAD

**Issue by alisherWork** [platformio/platformio-core-installer#3100] opened 2023-11-02 06:40 UTC
PS C:\Users\Administrator> python get-platformio.py
Installer version: 1.2.1
Platform: Windows-10
Python version: 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)]
Python path: C:\Users\Administrator\AppData\Local\Programs\Python\Python312\python.exe
Creating a virtual environment at C:\Users\Administrator\.platformio\penv
C:\Users\Administrator\AppData\Local\Programs\Python\Python312\python.exe
Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues
PS C:\Users\Administrator>

**Comment by ivankravets** [comment] 2024-01-06 12:22
Duplicate of https://github.com/platformio/platformio-core-installer/issues/3111

**Closed by ivankravets** 2024-01-06 12:22 UTC
