### ISSUE TITLE
Istanller manager

### ISSUE THREAD

**Issue by DikiFive** [platformio/platformio-core-installer#2252] opened 2022-07-02 13:43 UTC
Error: Could not start PIO Home server: Error: timeout at c:\Users\14185\.vscode\extensions\platformio.platformio-ide-2.5.0\node_modules\platformio-node-helpers\dist\index.js:1:9932...

**Comment by ivankravets** [comment] 2022-07-02 13:44
Duplicate of https://github.com/platformio/platformio-core-installer/issues/2246

**Closed by ivankravets** 2022-07-02 13:44 UTC
