### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by sjrshiwo** [platformio/platformio-core-installer#3099] opened 2023-11-01 13:59 UTC
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.83.1
  PIO IDE: v3.3.1
  System: Windows_NT, 10.0.22621, x64

  %23 Exception
  ```
  Error: ERROR: Could not find a version that satisfies the requirement pyelftools==0.30 (from platformio) (from versions: 0.20, 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29)
ERROR: No matching distribution found for pyelftools==0.30
WARNING: There was an error checking the latest version of pip.
Error: Could not install PlatformIO Core: If you have antivirus/firewall/defender software in a system, try to disable it for a while.
 Command '['C:\\Users\\sjrsjr\\.platformio\\penv\\Scripts\\python.exe', '-m', 'pip', 'install', '-U', 'https://github.com/platformio/platformio/archive/develop.zip']' returned non-zero exit status 1.
 -> Installer version: 1.2.1
Platform: Windows-10
Python version: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
Python path: C:\Users\sjrsjr\.platformio\python3\python.exe
Creating a virtual environment at C:\Users\sjrsjr\.platformio\penv
Updating Python package manager (PIP) in a virtual environment
PIP has been successfully updated!
Virtual environment has been successfully created!
Installing a development version of PlatformIO Core
Looking in indexes: https://repo.huaweicloud.com/repository/pypi/simple
Collecting https://github.com/platformio/platformio/archive/develop.zip
  Using cached https://github.com/platformio/platformio/archive/develop.zip
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting bottle==0.12.*
  Using cached https://repo.huaweicloud.com/repository/pypi/packages/ef/74/39f45da835b8654cfa66ccf6a65cea38d99f940db0a5e0d985de4723a1c9/bottle-0.12.24-py3-none-any.whl (90 kB)
Collecting click<=8.2,>=8.0.4
  Using cached https://repo.huaweicloud.com/repository/pypi/packages/00/2e/d53fa4befbf2cfa713304affc7ca780ce4fc1fd8710527771b58311a3229/click-8.1.7-py3-none-any.whl (97 kB)
Collecting colorama
  Using cached https://repo.huaweicloud.com/repository/pypi/packages/77/8b/7550e87b2d308a1b711725dfaddc19c695f8c5fa413c640b2be01662f4e6/colorama-0.4.5-py2.py3-none-any.whl (16 kB)
Collecting marshmallow==3.*
  Using cached https://repo.huaweicloud.com/repository/pypi/packages/ae/53/980a20d789029329fdf1546c315f9c92bf862c7f3e7294e3667afcc464f5/marshmallow-3.19.0-py3-none-any.whl (49 kB)

	at c:\Users\sjrsjr\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5300
	at ChildProcess.c (c:\Users\sjrsjr\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4598)
	at ChildProcess.emit (node:events:513:28)
	at ChildProcess.emit (node:domain:489:12)
	at maybeClose (node:internal/child_process:1091:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)
  ```

**Comment by ivankravets** [comment] 2024-01-06 11:29
Duplicate of https://github.com/platformio/platformio-core-installer/issues/3129

**Closed by ivankravets** 2024-01-06 11:29 UTC
