### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by yunfei-CMYK** [platformio/platformio-core-installer#3117] opened 2023-11-26 13:56 UTC
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.84.2
  PIO IDE: v3.3.1
  System: Windows_NT, 10.0.22621, x64

  %23 Exception
  ```
  Error:   error: subprocess-exited-with-error
  
  pip subprocess to install build dependencies did not run successfully.
  exit code: 1
  
  [5 lines of output]
  ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
  ERROR: No matching distribution found for setuptools>=40.8.0
  
  [notice] A new release of pip is available: 23.1.2 -> 23.3.1
  [notice] To update, run: C:\Users\JLF\.platformio\penv\Scripts\python.exe -m pip install --upgrade pip
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

pip subprocess to install build dependencies did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 23.1.2 -> 23.3.1
[notice] To update, run: C:\Users\JLF\.platformio\penv\Scripts\python.exe -m pip install --upgrade pip
Error: Could not install PlatformIO Core: If you have antivirus/firewall/defender software in a system, try to disable it for a while.
 Command '['C:\\Users\\JLF\\.platformio\\penv\\Scripts\\python.exe', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.2.1
Platform: Windows-10
Python version: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
Python path: C:\Users\JLF\.platformio\python3\python.exe
Creating a virtual environment at C:\Users\JLF\.platformio\penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core
Collecting platformio
  Using cached platformio-6.1.11-py3-none-any.whl (416 kB)
Collecting bottle==0.12.* (from platformio)
  Using cached bottle-0.12.25-py3-none-any.whl (90 kB)
Collecting click<=8.2,>=8.0.4 (from platformio)
  Using cached click-8.1.7-py3-none-any.whl (97 kB)
Collecting colorama (from platformio)
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting marshmallow==3.* (from platformio)
  Using cached marshmallow-3.20.1-py3-none-any.whl (49 kB)
Collecting pyelftools==0.29 (from platformio)
  Downloading pyelftools-0.29-py2.py3-none-any.whl (174 kB)
     ------------------------------------- 174.3/174.3 kB 52.2 kB/s eta 0:00:00
Collecting pyserial==3.5.* (from platformio)
  Downloading pyserial-3.5-py2.py3-none-any.whl (90 kB)
     --------------------------------------- 90.6/90.6 kB 19.3 kB/s eta 0:00:00
Collecting requests==2.* (from platformio)
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting semantic-version==2.10.* (from platformio)
  Downloading semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
Collecting tabulate==0.* (from platformio)
  Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
Collecting ajsonrpc==1.2.* (from platformio)
  Downloading ajsonrpc-1.2.0-py3-none-any.whl (22 kB)
Collecting starlette<0.32,>=0.19 (from platformio)
  Downloading starlette-0.31.1-py3-none-any.whl (69 kB)
     --------------------------------------- 69.9/69.9 kB 15.0 kB/s eta 0:00:00
INFO: pip is looking at multiple versions of platformio to determine which version is compatible with other requirements. This could take a while.
Collecting platformio
  Downloading platformio-6.1.10-py3-none-any.whl (416 kB)
     ------------------------------------- 416.9/416.9 kB 83.4 kB/s eta 0:00:00
  Downloading platformio-6.1.9-py3-none-any.whl (418 kB)
     ------------------------------------ 418.9/418.9 kB 105.0 kB/s eta 0:00:00
Collecting aiofiles>=0.8.0 (from platformio)
  Downloading aiofiles-23.2.1-py3-none-any.whl (15 kB)
Collecting marshmallow==3.19.* (from platformio)
  Downloading marshmallow-3.19.0-py3-none-any.whl (49 kB)
     --------------------------------------- 49.1/49.1 kB 71.0 kB/s eta 0:00:00
Collecting starlette==0.28.* (from platformio)
  Downloading starlette-0.28.0-py3-none-any.whl (68 kB)
     --------------------------------------- 68.9/68.9 kB 69.6 kB/s eta 0:00:00
Collecting platformio
  Downloading platformio-6.1.8-py3-none-any.whl (418 kB)
     ------------------------------------- 418.9/418.9 kB 73.5 kB/s eta 0:00:00
  Downloading platformio-6.1.7-py3-none-any.whl (418 kB)
     ------------------------------------- 419.0/419.0 kB 85.5 kB/s eta 0:00:00
Collecting pyelftools<1,>=0.27 (from platformio)
  Downloading pyelftools-0.30-py2.py3-none-any.whl (177 kB)
     ------------------------------------ 177.6/177.6 kB 108.2 kB/s eta 0:00:00
Collecting urllib3<2 (from platformio)
  Downloading urllib3-1.26.18-py2.py3-none-any.whl (143 kB)
     ------------------------------------ 143.8/143.8 kB 123.9 kB/s eta 0:00:00
Collecting aiofiles==23.1.* (from platformio)
  Downloading aiofiles-23.1.0-py3-none-any.whl (14 kB)
Collecting starlette==0.26.* (from platformio)
  Downloading starlette-0.26.1-py3-none-any.whl (66 kB)
     -------------------------------------- 66.9/66.9 kB 125.1 kB/s eta 0:00:00
Collecting platformio
  Downloading platformio-6.1.6.tar.gz (236 kB)
     ------------------------------------ 236.4/236.4 kB 144.8 kB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'

	at c:\Users\JLF\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5300
	at ChildProcess.c (c:\Users\JLF\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4598)
	at ChildProcess.emit (node:events:513:28)
	at ChildProcess.emit (node:domain:489:12)
	at maybeClose (node:internal/child_process:1091:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)
  ```

**Comment by ivankravets** [comment] 2024-01-06 11:28
Duplicate of https://github.com/platformio/platformio-core-installer/issues/3129

**Closed by ivankravets** 2024-01-06 11:28 UTC
