### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by marcovannoord** [platformio/platformio-core-installer#2258] opened 2022-07-04 09:34 UTC
%23 Description of problem
  What i have tried already:
  - Delete the whole .platformio folder and then open VS Code again, to make sure i start off with a clean slate. 
  - After getting this error, restart VS Code to see if the problem changes, but it remains the same

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.68.1
  PIO IDE: v2.5.0
  System: Windows_NT, 10.0.19044, x64

  %23 Exception
  ```
  Error: Error: Compatible PlatformIO Core not found.
Reason: Could not run `C:\Users\Marco\.platformio\penv\Scripts\platformio.exe --help`.
Error: Error: Traceback (most recent call last):

  File "C:\Users\Marco\.platformio\penv\lib\site-packages\platformio\__main__.py", line 102, in main

    cli()  %23 pylint: disable=no-value-for-parameter

  File "C:\Users\Marco\.platformio\penv\lib\site-packages\click\core.py", line 1130, in __call__

    return self.main(*args, **kwargs)

  File "C:\Users\Marco\.platformio\penv\lib\site-packages\click\core.py", line 1054, in main

    with self.make_context(prog_name, args, **extra) as ctx:

  File "C:\Users\Marco\.platformio\penv\lib\site-packages\click\core.py", line 920, in make_context

    self.parse_args(ctx, args)

  File "C:\Users\Marco\.platformio\penv\lib\site-packages\click\core.py", line 1613, in parse_args

    rest = super().parse_args(ctx, args)

  File "C:\Users\Marco\.platformio\penv\lib\site-packages\click\core.py", line 1378, in parse_args

    value, args = param.handle_parse_result(ctx, opts, args)

  File "C:\Users\Marco\.platformio\penv\lib\site-packages\click\core.py", line 2360, in handle_parse_result

    value = self.process_value(ctx, value)

  File "C:\Users\Marco\.platformio\penv\lib\site-packages\click\core.py", line 2322, in process_value

    value = self.callback(ctx, self, value)

  File "C:\Users\Marco\.platformio\penv\lib\site-packages\click\core.py", line 1273, in show_help

    echo(ctx.get_help(), color=ctx.color)

  File "C:\Users\Marco\.platformio\penv\lib\site-packages\click\core.py", line 699, in get_help

    return self.command.get_help(self)

  File "C:\Users\Marco\.platformio\penv\lib\site-packages\click\core.py", line 1298, in get_help

    self.format_help(ctx, formatter)

  File "C:\Users\Marco\.platformio\penv\lib\site-packages\click\core.py", line 1331, in format_help

    self.format_options(ctx, formatter)

  File "C:\Users\Marco\.platformio\penv\lib\site-packages\click\core.py", line 1533, in format_options

    self.format_commands(ctx, formatter)

  File "C:\Users\Marco\.platformio\penv\lib\site-packages\click\core.py", line 1586, in format_commands

    cmd = self.get_command(ctx, subcommand)

  File "C:\Users\Marco\.platformio\penv\lib\site-packages\platformio\cli.py", line 80, in get_command

    module = importlib.import_module(commands[cmd_name])

  File "C:\Users\Marco\.platformio\python3\lib\importlib\__init__.py", line 127, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load

  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 850, in exec_module

  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "C:\Users\Marco\.platformio\penv\lib\site-packages\platformio\commands\ci.py", line 24, in <module>

    from platformio.project.commands.init import project_init_cmd, validate_boards

  File "C:\Users\Marco\.platformio\penv\lib\site-packages\platformio\project\commands\init.py", line 55, in <module>

    @click.option("--ide", type=click.Choice(ProjectGenerator.get_supported_ides()))

  File "C:\Users\Marco\.platformio\penv\lib\site-packages\platformio\project\integration\generator.py", line 56, in get_supported_ides

    [

  File "C:\Users\Marco\.platformio\penv\lib\site-packages\platformio\project\integration\generator.py", line 56, in <listcomp>

    [

  File "C:\Users\Marco\.platformio\python3\lib\pathlib.py", line 1160, in iterdir

    for name in self._accessor.listdir(self):

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Marco\\.platformio\\penv\\lib\\site-packages\\platformio\\project\\integration\\tpls'



============================================================



An unexpected error occurred. Further steps:



* Verify that you have the latest version of PlatformIO using

  `pip install -U platformio` command



* Try to find answer in FAQ Troubleshooting section

  https://docs.platformio.org/page/faq/index.html



* Report this problem to the developers

  https://github.com/platformio/platformio-core/issues



============================================================





	at c:\Users\Marco\.vscode\extensions\platformio.platformio-ide-2.5.0\node_modules\platformio-node-helpers\dist\index.js:1:5227
	at ChildProcess.c (c:\Users\Marco\.vscode\extensions\platformio.platformio-ide-2.5.0\node_modules\platformio-node-helpers\dist\index.js:1:5121)
	at ChildProcess.emit (node:events:390:28)
	at ChildProcess.emit (node:domain:475:12)
	at ChildProcess.cp.emit (c:\Users\Marco\.vscode\extensions\platformio.platformio-ide-2.5.0\node_modules\cross-spawn\lib\enoent.js:34:29)
	at maybeClose (node:internal/child_process:1064:16)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
  ```

**Comment by ivankravets** [comment] 2022-07-04 10:52
Duplicate of https://github.com/platformio/platformio-core-installer/issues/2259

**Closed by ivankravets** 2022-07-04 10:52 UTC
