### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Gravifer** [platformio/platformio-core-installer#205] opened 2020-10-13 04:09 UTC
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.50.0
  PIO IDE: v2.1.0
  System: Linux, 5.3.0-59-generic, x64

  %23 Exception
  ```
  Error: Error: Can not install PlatformIO Core due to a missed `distutils` package in your Python installation.
Please install this package manually using the OS package manager. For example:

$ apt-get install python3-distutils

(MAY require administrator access `sudo`)
 -> Installer version: 0.3.5
Platform: Linux-5.3.0-59-generic-x86_64-with-glibc2.10
Python version: 3.8.3 (default, Jul  2 2020, 16:21:59) 
[GCC 7.3.0]
Python path: /home/jhma/tools/anaconda3/bin/python3
Creating a virtual environment at /home/jhma/.platformio/penv

	at /home/jhma/.vscode-server/extensions/platformio.platformio-ide-2.1.0/node_modules/platformio-node-helpers/dist/index.js:1:4849
	at ChildProcess.s (/home/jhma/.vscode-server/extensions/platformio.platformio-ide-2.1.0/node_modules/platformio-node-helpers/dist/index.js:1:4745)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  ```

**Comment by ivankravets** [comment] 2020-10-16 10:45
Duplicate of https://github.com/platformio/platformio-core-installer/issues/85

**Closed by ivankravets** 2020-10-16 10:45 UTC
