### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by towzh** [platformio/platformio-core-installer#2925] opened 2023-05-11 17:32 UTC
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.78.1
  PIO IDE: v3.1.1
  System: Windows_NT, 10.0.22621, x64

  %23 Exception
  ```
  Error: C:\Users\towzh\.platformio\.cache\tmp\.piocore-installer-nb161rtf\tmp1ogeu544\pioinstaller.zip\requests\__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
C:\Users\towzh\.platformio\.cache\tmp\.piocore-installer-nb161rtf\tmp1ogeu544\pioinstaller.zip\requests\__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
Traceback (most recent call last):
  File "C:\Users\towzh\.platformio\.cache\tmp\get-platformio-1.1.2.py", line 69, in <module>
    main()
  File "C:\Users\towzh\.platformio\.cache\tmp\get-platformio-1.1.2.py", line 61, in main
    bootstrap()
  File "C:\Users\towzh\.platformio\.cache\tmp\get-platformio-1.1.2.py", line 47, in bootstrap
    pioinstaller.__main__.main()
  File "C:\Users\towzh\.platformio\.cache\tmp\.piocore-installer-nb161rtf\tmp1ogeu544\pioinstaller.zip\pioinstaller\__main__.py", line 133, in main
  File "C:\Users\towzh\.platformio\.cache\tmp\.piocore-installer-nb161rtf\tmp1ogeu544\pioinstaller.zip\click\core.py", line 1128, in __call__
  File "C:\Users\towzh\.platformio\.cache\tmp\.piocore-installer-nb161rtf\tmp1ogeu544\pioinstaller.zip\click\core.py", line 1053, in main
  File "C:\Users\towzh\.platformio\.cache\tmp\.piocore-installer-nb161rtf\tmp1ogeu544\pioinstaller.zip\click\core.py", line 1637, in invoke
  File "C:\Users\towzh\.platformio\.cache\tmp\.piocore-installer-nb161rtf\tmp1ogeu544\pioinstaller.zip\click\core.py", line 1395, in invoke
  File "C:\Users\towzh\.platformio\.cache\tmp\.piocore-installer-nb161rtf\tmp1ogeu544\pioinstaller.zip\click\core.py", line 754, in invoke
  File "C:\Users\towzh\.platformio\.cache\tmp\.piocore-installer-nb161rtf\tmp1ogeu544\pioinstaller.zip\click\decorators.py", line 26, in new_func
  File "C:\Users\towzh\.platformio\.cache\tmp\.piocore-installer-nb161rtf\tmp1ogeu544\pioinstaller.zip\pioinstaller\__main__.py", line 61, in cli
  File "C:\Users\towzh\.platformio\.cache\tmp\.piocore-installer-nb161rtf\tmp1ogeu544\pioinstaller.zip\pioinstaller\core.py", line 70, in install_platformio_core
  File "C:\Users\towzh\.platformio\.cache\tmp\.piocore-installer-nb161rtf\tmp1ogeu544\pioinstaller.zip\pioinstaller\core.py", line 98, in _install_platformio_core
  File "C:\Users\towzh\.platformio\.cache\tmp\.piocore-installer-nb161rtf\tmp1ogeu544\pioinstaller.zip\pioinstaller\penv.py", line 71, in create_core_penv
  File "C:\Users\towzh\.platformio\.cache\tmp\.piocore-installer-nb161rtf\tmp1ogeu544\pioinstaller.zip\pioinstaller\penv.py", line 141, in init_state
  File "C:\Program Files\Inkscape\lib\python3.10\subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\Inkscape\lib\python3.10\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Inkscape\lib\python3.10\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Inkscape\lib\python3.10\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
 -> Installer version: 1.1.2
Platform: Windows-10
Python version: 3.10.8 (main, Nov  6 2022, 23:27:16)  [GCC 12.2.0 64 bit (AMD64)]
Python path: C:\Program Files\Inkscape\bin\python.exe
Creating a virtual environment at C:\Users\towzh\.platformio\penv

	at c:\Users\towzh\.vscode\extensions\platformio.platformio-ide-3.1.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5303
	at ChildProcess.o (c:\Users\towzh\.vscode\extensions\platformio.platformio-ide-3.1.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4601)
	at ChildProcess.emit (node:events:513:28)
	at ChildProcess.emit (node:domain:489:12)
	at maybeClose (node:internal/child_process:1112:16)
	at ChildProcess._handle.onexit (node:internal/child_process:304:5)
  ```

**Comment by ivankravets** [comment] 2023-05-31 12:14
Duplicate of https://github.com/platformio/platformio-vscode-ide/issues/884

**Closed by ivankravets** 2023-05-31 12:14 UTC
